export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const RESTAURANTS_ERROR = "RESTAURANTS_ERROR";
export const GET_CITIES_REQUESTED = "GET_CITIES_REQUESTED";
export const GET_CITIES_FAILED = "GET_CITIES_FAILED";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";
export const LOADING_RESTAURANTS = "LOADING_RESTAURANTS";
