export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const RESTAURANTS_ERROR = "RESTAURANTS_ERROR";
export const GET_CITIES = "GET_CITIES";
export const LOADING_RESTAURANTS = "LOADING_RESTAURANTS";
